### PR TITLE
Refactor Scripts

### PR DESCRIPTION
**Pull request by justinwp**
see #66

### CODE REVIEW

**Comment by justinwp** [comment]
This causes breaking changes to script users if they upgrade to the newer version of this library.

**Comment by aliasmrchips** [comment]
Does one have to do `descarteslabs metadata search` (for example). Perhaps shortening the top-level command to `dl`?

**Comment by justinwp** [comment]
The user can easily link, probably better to avoid collisions.

**Comment by aliasmrchips** [comment]
This looks good to me otherwise.

**Pull request merged**
