### PR TITLE
Add bands and products search/get endpoints

### PR DESCRIPTION
**Pull request by hrfuller**

### CODE REVIEW

**Comment by samskillman** [comment]
This looks pretty good. I think we probably want to avoid doctests directly on the description field, which I think we'll make updates/improvements to. Other than that I'll test things out a bit and report back.

**Comment by hrfuller** [comment]
If there are fields that are useful to search on that are missing let me know.

**Comment by hrfuller** [comment]
I need to use this in descarteslabs/platform#204 can we merge it?

**Comment by hrfuller** [comment]
allow a list of bands to be passed in the products search helper.

**Pull request merged**
